// 자사몰사관학교 기본 뉴스레터 템플릿 (Unlayer JSON 형식)
// 600px, 테두리 없음, Pretendard 폰트, 흰색 배경
// 스티비/마켓핏랩 스타일 — 깔끔하고 읽기 쉬운 레이아웃
// Last verified: 2026-02-11

export const BS_CAMP_DEFAULT_TEMPLATE = {
  body: {
    id: "bs-camp-default",
    rows: [
      // ─── Row 1: 헤더 (자사몰사관학교 로고 + 빨간 라인) ───
      {
        id: "row-header",
        cells: [1],
        columns: [
          {
            id: "col-header",
            contents: [
              {
                id: "content-logo",
                type: "text",
                values: {
                  containerPadding: "24px 24px 16px",
                  anchor: "",
                  textAlign: "center",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_logo", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 20px; line-height: 140%;"><strong><span style="color: #f75d5d; font-size: 20px; line-height: 28px;">자사몰사관학교</span></strong></p>',
                },
              },
              {
                id: "content-divider-header",
                type: "divider",
                values: {
                  width: "100%",
                  border: {
                    borderTopWidth: "2px",
                    borderTopStyle: "solid",
                    borderTopColor: "#F75D5D",
                  },
                  textAlign: "center",
                  containerPadding: "0px 24px 0px",
                  anchor: "",
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_divider_header", htmlClassNames: "u_content_divider" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_header", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_header", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 2: 제목 블록 ───
      {
        id: "row-title",
        cells: [1],
        columns: [
          {
            id: "col-title",
            contents: [
              {
                id: "content-title",
                type: "text",
                values: {
                  containerPadding: "32px 24px 8px",
                  anchor: "",
                  textAlign: "left",
                  lineHeight: "150%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_title", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<h1 style="font-size: 22px; line-height: 150%;"><strong><span style="color: #1a1a1a; font-size: 22px; line-height: 33px;">뉴스레터 제목을 입력하세요</span></strong></h1>',
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_title", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_title", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 3: 본문 텍스트 (상단) ───
      {
        id: "row-body-text-1",
        cells: [1],
        columns: [
          {
            id: "col-body-text-1",
            contents: [
              {
                id: "content-body-text-1",
                type: "text",
                values: {
                  containerPadding: "16px 24px",
                  anchor: "",
                  textAlign: "left",
                  lineHeight: "180%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#F75D5D",
                    linkHoverColor: "#E54949",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_body1", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 15px; line-height: 180%;"><span style="color: #333333; font-size: 15px; line-height: 27px;">안녕하세요. 자사몰사관학교입니다.</span></p>\n<p style="font-size: 15px; line-height: 180%;"><span style="color: #333333; font-size: 15px; line-height: 27px;">여기에 뉴스레터 본문 내용을 작성해주세요. 독자에게 전달하고 싶은 핵심 메시지를 간결하게 정리하면 좋습니다.</span></p>',
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_body1", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_body1", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 4: 이미지 블록 (풀와이드) ───
      {
        id: "row-image",
        cells: [1],
        columns: [
          {
            id: "col-image",
            contents: [
              {
                id: "content-image",
                type: "image",
                values: {
                  containerPadding: "16px 24px",
                  anchor: "",
                  src: {
                    url: "https://via.placeholder.com/600x300/f5f5f5/999999?text=Image",
                    width: 600,
                    height: 300,
                  },
                  textAlign: "center",
                  altText: "뉴스레터 이미지",
                  action: {
                    name: "web",
                    values: { href: "", target: "_blank" },
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_image_main", htmlClassNames: "u_content_image" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  fullWidth: true,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_image", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_image", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 5: 본문 텍스트 (하단) ───
      {
        id: "row-body-text-2",
        cells: [1],
        columns: [
          {
            id: "col-body-text-2",
            contents: [
              {
                id: "content-body-text-2",
                type: "text",
                values: {
                  containerPadding: "16px 24px",
                  anchor: "",
                  textAlign: "left",
                  lineHeight: "180%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#F75D5D",
                    linkHoverColor: "#E54949",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_body2", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 15px; line-height: 180%;"><span style="color: #333333; font-size: 15px; line-height: 27px;">추가 본문 내용을 여기에 작성하세요. 이미지 아래에 더 자세한 설명이나 부가 정보를 제공할 수 있습니다.</span></p>',
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_body2", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_body2", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 6: CTA 버튼 ───
      {
        id: "row-cta",
        cells: [1],
        columns: [
          {
            id: "col-cta",
            contents: [
              {
                id: "content-cta-button",
                type: "button",
                values: {
                  containerPadding: "16px 24px 32px",
                  anchor: "",
                  href: {
                    name: "web",
                    values: { href: "https://bscamp.co.kr", target: "_blank" },
                  },
                  buttonColors: {
                    color: "#ffffff",
                    backgroundColor: "#F75D5D",
                    hoverColor: "#ffffff",
                    hoverBackgroundColor: "#E54949",
                  },
                  size: {
                    autoWidth: false,
                    width: "100%",
                  },
                  textAlign: "center",
                  lineHeight: "140%",
                  padding: "14px 32px",
                  border: {},
                  borderRadius: "8px",
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_button_cta", htmlClassNames: "u_content_button" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<span style="font-size: 16px; line-height: 22.4px;"><strong>전체 아티클 읽기 &rarr;</strong></span>',
                  calculatedWidth: 552,
                  calculatedHeight: 50,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_cta", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#ffffff",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_cta", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },

      // ─── Row 7: 푸터 (자사몰 사관학교 정보 + 수신거부) ───
      {
        id: "row-footer",
        cells: [1],
        columns: [
          {
            id: "col-footer",
            contents: [
              {
                id: "content-footer-divider",
                type: "divider",
                values: {
                  width: "100%",
                  border: {
                    borderTopWidth: "1px",
                    borderTopStyle: "solid",
                    borderTopColor: "#eeeeee",
                  },
                  textAlign: "center",
                  containerPadding: "0px 24px",
                  anchor: "",
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_divider_footer", htmlClassNames: "u_content_divider" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
              {
                id: "content-footer-text",
                type: "text",
                values: {
                  containerPadding: "24px 24px 8px",
                  anchor: "",
                  textAlign: "center",
                  lineHeight: "170%",
                  linkStyle: {
                    inherit: false,
                    linkColor: "#999999",
                    linkHoverColor: "#666666",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_footer", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 12px; line-height: 170%;"><span style="color: #a4a4a4; font-size: 12px; line-height: 20.4px;">자사몰 사관학교</span></p>\n<p style="font-size: 12px; line-height: 170%;"><span style="color: #999999; font-size: 12px; line-height: 20.4px;">본 메일은 자사몰사관학교에서 발송한 뉴스레터입니다.</span></p>\n<p style="font-size: 12px; line-height: 170%;"><span style="color: #999999; font-size: 12px; line-height: 20.4px;">수신을 원하지 않으시면 <a href="{{UNSUBSCRIBE_URL}}" target="_blank" style="color: #999999; text-decoration: underline;">수신거부</a>를 클릭해주세요.</span></p>',
                },
              },
              {
                id: "content-footer-copyright",
                type: "text",
                values: {
                  containerPadding: "0px 24px 24px",
                  anchor: "",
                  textAlign: "center",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: { htmlID: "u_content_text_copyright", htmlClassNames: "u_content_text" },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 11px; line-height: 140%;"><span style="color: #aaaaaa; font-size: 11px; line-height: 15.4px;">&copy; 2026 자사몰사관학교. All rights reserved.</span></p>',
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_footer", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "#f7f7f7",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_footer", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
    ],
    headers: [],
    footers: [],
    values: {
      popupPosition: "center",
      popupWidth: "600px",
      popupHeight: "auto",
      borderRadius: "0px",
      contentAlign: "center",
      contentVerticalAlign: "center",
      contentWidth: "600px",
      fontFamily: {
        label: "Pretendard",
        value: "'Pretendard', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        url: "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css",
        defaultFont: true,
      },
      textColor: "#333333",
      popupBackgroundColor: "#FFFFFF",
      popupBackgroundImage: {
        url: "",
        fullWidth: true,
        repeat: "no-repeat",
        size: "custom",
        position: "center",
      },
      popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
      popupCloseButton_position: "top-right",
      popupCloseButton_backgroundColor: "#DDDDDD",
      popupCloseButton_iconColor: "#000000",
      popupCloseButton_borderRadius: "0px",
      popupCloseButton_margin: "0px",
      popupCloseButton_action: {
        name: "close_popup",
        attrs: {
          onClick:
            "document.querySelector('.u-teleporter-close').click();",
        },
      },
      backgroundColor: "#ffffff",
      preheaderText: "",
      linkStyle: {
        body: true,
        linkColor: "#F75D5D",
        linkHoverColor: "#E54949",
        linkUnderline: true,
        linkHoverUnderline: true,
      },
      _meta: { htmlID: "u_body", htmlClassNames: "u_body" },
    },
  },
};
