// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pending">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/subscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/subscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/agent-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agent-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/agent-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/answers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/answers">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/answers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/content/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/content/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/email/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/email/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/email/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/email">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/invites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invites">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/invites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/organic/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/organic/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/organic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/organic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/owner-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/owner-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/owner-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/protractor/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/protractor/benchmarks">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/protractor/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/protractor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/protractor">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/protractor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/admin/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/terminal">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/creatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creatives">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/creatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/notices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/notices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/notices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notices">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/notices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/posts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/posts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/posts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts/new">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/posts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/protractor/competitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/protractor/competitor">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/protractor/competitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/protractor/creatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/protractor/creatives">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/protractor/creatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/protractor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/protractor">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/protractor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/questions/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/questions/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/questions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/questions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/questions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions/new">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/questions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reviews/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reviews/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reviews/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/new">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reviews/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/accounts/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/accounts/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/accounts/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/backfill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/backfill">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/backfill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog-benchmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog-benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog-benchmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/[id]/newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content/[id]/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/[id]/newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/summarize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content/summarize">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/summarize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-benchmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-benchmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-clusters/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-clusters/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-clusters/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-clusters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-clusters">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-clusters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-fatigue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-fatigue">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-fatigue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-lp-consistency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-lp-consistency">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-lp-consistency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-saliency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-saliency">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-saliency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creative-similarity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creative-similarity">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creative-similarity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/curation/backfill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/curation/backfill">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/curation/backfill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/curation/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/curation/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/curation/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/ai-write/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/ai-write">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/ai-write/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/recipients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/recipients">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/recipients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/embed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/embed">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/embed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/forbidden-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forbidden-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/forbidden-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/gsc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gsc">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/gsc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/keyword-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/keyword-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/keyword-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/knowledge/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/knowledge/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/knowledge/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/post-diagnosis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/post-diagnosis">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/post-diagnosis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/protractor/collect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/protractor/collect">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/protractor/collect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/protractor/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/protractor/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/protractor/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reembed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reembed">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reembed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/style-learn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/style-learn">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/style-learn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-dashboard/background/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-dashboard/background/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-dashboard/background/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-dashboard/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-dashboard/log">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-dashboard/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-dashboard/slack/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-dashboard/slack/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-dashboard/slack/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-dashboard/team/[teamId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-dashboard/team/[teamId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-dashboard/team/[teamId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/firebase-logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/firebase-logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/firebase-logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/firebase-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/firebase-session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/firebase-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/naver/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/naver/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/naver/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/analysis-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/analysis-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/analysis-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/brands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/brands">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/brands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/download-zip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/download-zip">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/download-zip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/monitors/[id]/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/monitors/[id]/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/monitors/[id]/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/monitors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/monitors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/monitors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/monitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/monitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/monitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/pages">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/competitor/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitor/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/competitor/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creative/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/creative/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creative/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/creative/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/analyze-competitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/analyze-competitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/analyze-competitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/analyze-lp-saliency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/analyze-lp-saliency">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/analyze-lp-saliency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/backfill-ai-answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/backfill-ai-answers">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/backfill-ai-answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/cleanup-deleted/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-deleted">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/cleanup-deleted/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-benchmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-benchmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-benchmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-clicks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-clicks">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-clicks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-content">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-daily-1/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-daily-1">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-daily-1/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-daily-2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-daily-2">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-daily-2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-daily-3/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-daily-3">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-daily-3/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-daily-4/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-daily-4">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-daily-4/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-daily/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-daily">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-daily/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-mixpanel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-mixpanel">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-mixpanel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/collect-youtube/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/collect-youtube">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/collect-youtube/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/competitor-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/competitor-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/competitor-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/crawl-lps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/crawl-lps">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/crawl-lps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/creative-saliency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/creative-saliency">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/creative-saliency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/deepgaze-gemini/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/deepgaze-gemini">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/deepgaze-gemini/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/discover-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/discover-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/discover-accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/embed-creatives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/embed-creatives">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/embed-creatives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/organic-benchmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/organic-benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/organic-benchmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/precompute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/precompute">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/precompute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/process-media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/process-media">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/process-media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/publish-scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/publish-scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/publish-scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/sync-notion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-notion">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/sync-notion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/track-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/track-performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/track-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/video-saliency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/video-saliency">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/video-saliency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/video-scene-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/video-scene-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/video-scene-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diagnose">> = Specific
  const handler = {} as typeof import("../../src/app/api/diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/blog-benchmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/blog-benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/blog-benchmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/forbidden-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/forbidden-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/forbidden-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/keyword-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/keyword-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/keyword-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/post-diagnosis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/post-diagnosis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/post-diagnosis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ext/profanity-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ext/profanity-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/ext/profanity-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/facebook/page-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/facebook/page-info">> = Specific
  const handler = {} as typeof import("../../src/app/api/facebook/page-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/add-webinar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/add-webinar">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/add-webinar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invite/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invite/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/invite/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/benchmarks/collect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/benchmarks/collect">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/benchmarks/collect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/benchmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/benchmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/benchmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/collect-daily/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/collect-daily">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/collect-daily/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/collect-mixpanel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/collect-mixpanel">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/collect-mixpanel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/overlap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/overlap">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/overlap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/save-secret/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/save-secret">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/save-secret/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protractor/total-value/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protractor/total-value">> = Specific
  const handler = {} as typeof import("../../src/app/api/protractor/total-value/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa-chatbot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa-chatbot">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa-chatbot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/terminal/sessions/[id]/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal/sessions/[id]/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/terminal/sessions/[id]/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/terminal/sessions/[id]/input/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal/sessions/[id]/input">> = Specific
  const handler = {} as typeof import("../../src/app/api/terminal/sessions/[id]/input/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/terminal/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/terminal/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/terminal/slack-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal/slack-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/terminal/slack-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/unsplash/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsplash/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/unsplash/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify-business/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify-business">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify-business/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(main)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/protractor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/protractor">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/protractor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
